// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJnLV1eTourZ97RS2VVT9q5TLPYyOo5VI',
    appId: '1:283834237547:web:67e5dbbd8a8def5b11a72e',
    messagingSenderId: '283834237547',
    projectId: 'vote-marker',
    authDomain: 'vote-marker.firebaseapp.com',
    storageBucket: 'vote-marker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlO5vR3Ub4iogflY7LAKlBGa9-T6UyNx4',
    appId: '1:283834237547:android:9cdf2889c40e645311a72e',
    messagingSenderId: '283834237547',
    projectId: 'vote-marker',
    storageBucket: 'vote-marker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfGzB0PM1EiBAOR6hXeAPakMjM5sY-8mA',
    appId: '1:283834237547:ios:011e8f1a02f4931b11a72e',
    messagingSenderId: '283834237547',
    projectId: 'vote-marker',
    storageBucket: 'vote-marker.appspot.com',
    iosClientId: '283834237547-smcqv2vcdpsm8uf80a0fb3jkkb244aur.apps.googleusercontent.com',
    iosBundleId: 'com.example.voteMarker',
  );
}
